services:
  bitcoin-core:
    container_name: bitcoin-core
    restart: unless-stopped
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/raine-works/bitcoin-core:latest
    command: /bin/bash -c "trap 'bitcoin-cli stop; sleep 5' SIGTERM && bitcoind"
    ports:
      - 8333:8333
    volumes:
      - btc_core_data:/mnt/btc_core
    networks:
      - btc_core_network

volumes:
  btc_core_data:
    driver: local

networks:
  btc_core_network:
    driver: bridge
