services:
  bitcoin-core:
    container_name: bitcoin-core
    restart: unless-stopped
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/raine-works/bitcoin-core:latest
    command: bitcoind
    ports:
      - 8333:8333
    volumes:
      - /mnt/btc_core/btc_data:/mnt/btc_core/btc_data
    networks:
      - btc_core_network

networks:
  btc_core_network:
    driver: bridge
